workflows:
  ios-workflow:
    scripts:
      - name: iOS Workflow 
        script: echo "Hello Codemagician!"
      - name: Add provisioning profiles
        script: |
          set -e # exit on first failed command

          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          echo "BookDosirockM" | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
      - name: Add signing certificate
        script: |
          set -e # exit on first failed command

          echo "bookdosirockm.p12" | base64 --decode > /tmp/certificate.p12
          keychain initialize
          keychain add-certificates \
              --certificate /tmp/certificate.p12 \
              --certificate-password "s3FqqUup"
      - name: Increment build number
        script: agvtool new-version -all $BUILD_NUMBER
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa \
                    --workspace "${XCODE_WORKSPACE?}" \
                    --scheme "${XCODE_SCHEME?}"
    artifacts:
      - build/ios/ipa/*.ipa

    environment:
      xcode: 14.0
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bookcosmos.BookDosirockM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
